<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>true</GenerateProgramFile>
    <IsTestProject>true</IsTestProject>
    <WarningsAsErrors>FS0025</WarningsAsErrors>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Include="paket.references" />
    <Compile Include="Helpers.fs" />
    <Compile Include="Tests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bowling\Bowling.fsproj" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>